spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system_monitor?
      useSSL=false&
      serverTimezone=UTC&
      allowPublicKeyRetrieval=true

    username: user
    password: user
  mail:
    host: smtp.gmail.com
    port: 587
    username: seenivasan.offl.ac@gmail.com
    password: vgwttmzxnnktdlbi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
groq:
  api-key: ${GROQ_API_KEY}





